name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app-zip
          path: ${{ github.workspace }}/app
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract artifact
        shell: powershell
        run: |
          Expand-Archive -Path "${{ github.workspace }}\app\node-app-zip.zip" -DestinationPath "${{ github.workspace }}\app" -Force

      - name: Install dependencies
        shell: powershell
        run: |
          cd "${{ github.workspace }}\app"
          npm install --legacy-peer-deps

      - name: Start app with PM2
        shell: powershell
        run: |
          cd "${{ github.workspace }}\app"
          pm2 delete chat-app || echo "No existing process"
          pm2 start src/index.js --name chat-app --watch
