name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app-zip
          path: .

      - name: Unzip artifact
        run: unzip app.zip -d app

      - name: Install dependencies
        run: |
          cd app
          npm install

      - name: Install PM2 globally
        run: npm install -g pm2

      - name: Start app with PM2
        run: |
          cd app
          pm2 start src/index.js --name chat-app --watch
