name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app-zip
          path: .

      - name: Unzip app
        run: Expand-Archive -Path app.zip -DestinationPath . -Force

      - name: Install dependencies
        run: npm install

      - name: Restart app with PM2
        run: |
          pm2 delete chat-app || echo "No previous process"
          pm2 start src/index.js --name chat-app --watch
