name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint (optional)
        run: npm run lint || echo "no lint"

      - name: Tests (optional)
        run: npm test || echo "no tests"

      - name: Build (optional)
        run: npm run build || echo "no build"

      - name: Zip app
        run: zip -r app.zip . -x "*.git*"

      - name: Upload production artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app-zip           # <-- THE name CD will look for
          path: app.zip
